### PR TITLE
Use broccoli-asset-rev asset map for manifest

### LINKED ISSUE #102: Wrong manifest file paths
`fastboot-dist/package.json` looks like this:

```json
{
  "dependencies": {},
  "fastboot": {
    "moduleWhitelist": [],
    "manifest": {
      "appFile": "assets/fastboot-demo.js",
      "htmlFile": "index.html",
      "vendorFile": "assets/vendor.js"
    }
  }
}
```

should have been:

```json
{
  "dependencies": {},
  "fastboot": {
    "moduleWhitelist": [],
    "manifest": {
      "appFile": "assets/fastboot-demo-SHA.js",
      "htmlFile": "index.html",
      "vendorFile": "assets/vendor-SHA.js"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by tomdale**
`broccoli-asset-rev` works by renaming files inside fastboot-dist so that the file name contains an MD5 hash of their contents. Unfortunately, it is hardcoded to rewrite only specific files like index.html and therefore broke the FastBoot manifest in `fastboot-dist/package.json`.

This commit modifies FastBoot to run after broccoli-asset-rev, and use a generated asset map to update the FastBoot manifest to point to the fingerprinted assets.

Fixes #102

### CODE REVIEW

File: lib/broccoli/fastboot-config.js [hunk 1]
```diff
@@ -42,14 +62,35 @@ FastBootConfig.prototype.buildDependencies = function() {
...
     appFile: strip(outputPaths.app.js),
     htmlFile: strip(outputPaths.app.html),
     vendorFile: strip(outputPaths.vendor.js)
   };
+
+  var rewrittenAssets = this.readAssetManifest();
+
+  if (rewrittenAssets) {
+    ['appFile', 'vendorFile'].forEach(function(file) {
+      manifest[file] = rewrittenAssets.assets[manifest[file]];
```
Comment (rwjblue) [inline lib/broccoli/fastboot-config.js]: This needs to take into account the `prepend` that was provided to broccoli-asset-rev.  

If a prepend is present, it will be included in `rewrittenAssets.assets[manifest[file]]`.

**Comment by tomdale** [comment]
@jpadilla @danmcclain Let me know if this solves your issue.

**Comment by danmcclain** [comment]
@tomdale I can test tomorrow

**Comment by danmcclain** [comment]
@tomdale Sorry for the delay, but this did solve the issue WRT prod builds :+1:
